import time
from typing import Dict, Any, Optional, List
from llm.config import LLMConfig, get_default_llm_config
from llm.models import ExplanationInput, StructuredPlanExplanation, PlanExplanationResponse
from llm.providers.base import BaseLLMProvider
from llm.providers.gemini_provider import GeminiProvider
from llm.providers.groq_provider import GroqProvider
from llm.fallback import DeterministicExplanationEngine
from scoring.models import PlanSelectionResponse
from utils.logger import get_logger

logger = get_logger("plan_explanation_service")


class PlanExplanationService:
    """
    High-level orchestrator for AI Block Plan Natural-Language Intelligence.
    Executes a resilient fallback cascade:
        Primary Provider (Gemini)
                ↓ failure / timeout
        Secondary Provider (Groq)
                ↓ failure
        Deterministic Explanation Engine
    Guarantees explanation generation never fails or interrupts block dispatching.
    """

    def __init__(
        self,
        config: Optional[LLMConfig] = None,
        gemini_provider: Optional[BaseLLMProvider] = None,
        groq_provider: Optional[BaseLLMProvider] = None
    ):
        self.config = config or get_default_llm_config()
        self.gemini_provider = gemini_provider or GeminiProvider(self.config)
        self.groq_provider = groq_provider or GroqProvider(self.config)

    def get_provider_status(self) -> Dict[str, Any]:
        """Returns readiness status for all configured LLM providers."""
        return {
            "gemini": {
                "available": self.gemini_provider.is_available(),
                "model": self.gemini_provider.model_name,
                "has_key": self.config.has_gemini_key()
            },
            "groq": {
                "available": self.groq_provider.is_available(),
                "model": self.groq_provider.model_name,
                "has_key": self.config.has_groq_key()
            },
            "deterministic_fallback": {
                "available": True,
                "description": "Rule-based mathematical explanation generator"
            },
            "provider_order": self.config.provider_order
        }

    def explain_plan(
        self,
        input_data: ExplanationInput
    ) -> PlanExplanationResponse:
        """
        Generates a validated structured explanation for the input plan using the fallback cascade.
        """
        start_time = time.perf_counter()
        errors: List[str] = []

        # 1. Try configured providers in order (default: gemini -> groq)
        for provider_name in self.config.provider_order:
            provider: Optional[BaseLLMProvider] = None
            if provider_name == "gemini":
                provider = self.gemini_provider
            elif provider_name == "groq":
                provider = self.groq_provider

            if not provider or not provider.is_available():
                logger.debug("Provider '%s' unavailable, skipping.", provider_name)
                continue

            try:
                explanation = provider.explain_plan(input_data)
                latency_ms = round((time.perf_counter() - start_time) * 1000.0, 1)
                fallback_status = "PRIMARY_SUCCESS" if provider_name == self.config.provider_order[0] else "SECONDARY_FALLBACK_SUCCESS"
                logger.info("Plan explanation generated via %s (%s) in %.1fms", provider_name, provider.model_name, latency_ms)

                return PlanExplanationResponse(
                    success=True,
                    explanation=explanation,
                    provider_used=provider_name,
                    model_used=provider.model_name,
                    fallback_status=fallback_status,
                    latency_ms=latency_ms,
                    message=f"Plan explanation successfully generated by {provider_name.capitalize()} ({provider.model_name})."
                )

            except Exception as e:
                err_msg = f"{provider_name} failed: {str(e)}"
                logger.warning("Explanation attempt via %s failed: %s", provider_name, str(e))
                errors.append(err_msg)

        # 2. Both providers failed or unavailable -> Fall back to Deterministic Explanation Engine
        if self.config.enable_deterministic_fallback:
            logger.info("Engaging deterministic rule-based explanation engine (external LLMs unavailable or errored).")
            explanation = DeterministicExplanationEngine.generate(input_data)
            latency_ms = round((time.perf_counter() - start_time) * 1000.0, 1)

            status_msg = "Deterministic explanation generated."
            if errors:
                status_msg += f" (External LLM errors: {'; '.join(errors)})"

            return PlanExplanationResponse(
                success=True,
                explanation=explanation,
                provider_used="deterministic",
                model_used="rule-based-engine",
                fallback_status="DETERMINISTIC_FALLBACK",
                latency_ms=latency_ms,
                message=status_msg
            )

        # If deterministic fallback was disabled and external calls failed
        latency_ms = round((time.perf_counter() - start_time) * 1000.0, 1)
        raise RuntimeError(f"All LLM providers failed to generate explanation: {'; '.join(errors)}")

    def explain_selection_response(
        self,
        selection_response: PlanSelectionResponse,
        user_query: Optional[str] = None
    ) -> PlanExplanationResponse:
        """
        Convenience adapter: extracts ExplanationInput directly from Prompt 8 PlanSelectionResponse.
        """
        if not selection_response.selected_plan:
            raise ValueError("Cannot explain selection response: selected_plan is null or infeasible.")

        expl_data = selection_response.explanation_data
        if not expl_data:
            raise ValueError("Selection response missing structured explanation_data payload.")

        input_data = ExplanationInput(
            selected_plan=expl_data.selected_plan,
            strategy=expl_data.strategy,
            score=expl_data.score,
            corridor_code=selection_response.corridor_code,
            metrics=expl_data.metrics,
            key_decisions=expl_data.key_decisions,
            tradeoffs=expl_data.tradeoffs,
            scheduled_priority_tasks=expl_data.scheduled_priority_tasks,
            unscheduled_priority_tasks=expl_data.unscheduled_priority_tasks,
            major_constraints=expl_data.major_constraints,
            alternatives=expl_data.alternatives,
            user_query=user_query
        )

        return self.explain_plan(input_data)


def get_plan_explanation_service() -> PlanExplanationService:
    """Dependency provider for PlanExplanationService."""
    return PlanExplanationService()
