from typing import List, Dict, Any, Optional
from datetime import datetime
from pydantic import BaseModel, Field
from fastapi import APIRouter, Depends, HTTPException, status

from scoring.config import ScoringConfig, get_default_scoring_config
from scoring.models import PlanSelectionResponse, ScoredPlan
from scoring.service import PlanScoringService, get_plan_scoring_service
from optimizer.models import (
    OptimizationRequest,
    OptimizationPlanResult,
    MaintenanceRequestItem
)
from optimizer.service import RailwayOptimizerService, get_optimizer_service
from constraints.models import TrainMovementSummary, BlockWindowSummary
from utils.logger import get_logger

logger = get_logger("scoring_api")

router = APIRouter(prefix="/api/v1/scoring", tags=["Plan Scoring & Selection"])


class EvaluatePlansPayload(BaseModel):
    """Payload to evaluate, score, and rank pre-generated candidate block plans."""
    corridor_code: str = Field(default="NDLS-CNB", description="Railway corridor code")
    horizon_start: Optional[datetime] = Field(None, description="Planning horizon start timestamp")
    horizon_end: Optional[datetime] = Field(None, description="Planning horizon end timestamp")
    plans: List[OptimizationPlanResult] = Field(..., description="List of candidate plans generated by optimizer")
    requests: List[MaintenanceRequestItem] = Field(default_factory=list, description="Original list of maintenance requests")
    candidate_windows: List[BlockWindowSummary] = Field(default_factory=list, description="Available block windows")
    train_movements: List[TrainMovementSummary] = Field(default_factory=list, description="Scheduled train paths")
    scoring_config: Optional[ScoringConfig] = Field(None, description="Optional custom scoring weights and thresholds")


@router.get(
    "/config",
    response_model=Dict[str, Any],
    summary="Get active plan scoring configuration and objective weights",
    description="Returns weights for asset availability, risk priority, operational efficiency, block compactness, grouping, and overdue clearing."
)
def get_scoring_configuration(
    service: PlanScoringService = Depends(get_plan_scoring_service)
) -> Dict[str, Any]:
    """Returns active scoring weights and thresholds."""
    return {
        "active_weights": service.config.model_dump(),
        "normalized_weights": service.config.get_normalized_weights(),
        "min_acceptable_score": service.config.min_acceptable_score,
        "tie_breaker_priority": service.config.tie_breaker_priority
    }


@router.post(
    "/evaluate",
    response_model=PlanSelectionResponse,
    summary="Score, rank, and select the best block plan among candidate alternatives",
    description="Validates feasibility via Prompt 6, computes 13 metrics, scores 6 normalized dimensions, ranks, and analyzes trade-offs."
)
def evaluate_and_select_plan(
    payload: EvaluatePlansPayload,
    service: PlanScoringService = Depends(get_plan_scoring_service)
) -> PlanSelectionResponse:
    """Evaluates candidate plans and returns the winning plan with ranked alternatives and trade-offs."""
    try:
        # If custom scoring config was passed, instantiate service with it
        active_service = service
        if payload.scoring_config:
            active_service = PlanScoringService(config=payload.scoring_config)

        return active_service.select_best_plan(
            plans=payload.plans,
            requests=payload.requests,
            trains=payload.train_movements,
            windows=payload.candidate_windows,
            corridor_code=payload.corridor_code,
            horizon_start=payload.horizon_start,
            horizon_end=payload.horizon_end
        )
    except Exception as e:
        logger.error("Plan evaluation failure: %s", str(e), exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to score and select block plan: {str(e)}"
        )


@router.post(
    "/optimize-and-select",
    response_model=PlanSelectionResponse,
    summary="End-to-end: Optimize with OR-Tools, validate, score, rank, and select best plan",
    description="Executes CP-SAT block optimization across strategies, validates hard constraints, scores, ranks, and returns winning plan."
)
def optimize_and_select(
    request: OptimizationRequest,
    optimizer: RailwayOptimizerService = Depends(get_optimizer_service),
    scoring_service: PlanScoringService = Depends(get_plan_scoring_service)
) -> PlanSelectionResponse:
    """Runs OR-Tools solver and immediately scores and selects the best plan."""
    try:
        opt_response = optimizer.optimize_block_plan(request)
        if not opt_response.plans:
            raise HTTPException(
                status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
                detail="Optimizer failed to produce any candidate plans."
            )

        return scoring_service.select_best_plan(
            plans=opt_response.plans,
            requests=request.requests,
            trains=request.train_movements,
            windows=request.candidate_windows,
            corridor_code=request.corridor_code,
            horizon_start=request.horizon_start,
            horizon_end=request.horizon_end
        )
    except HTTPException:
        raise
    except Exception as e:
        logger.error("End-to-end optimize and select failure: %s", str(e), exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Optimization and scoring error: {str(e)}"
        )
