from typing import List, Dict, Any, Optional, Tuple
from datetime import datetime, timezone

from scoring.config import ScoringConfig, get_default_scoring_config
from scoring.models import (
    ScoredPlan,
    PlanRawMetrics,
    NormalizedScores,
    TradeOffItem,
    StructuredExplanationData,
    PlanSelectionResponse
)
from scoring.calculator import PlanMetricsCalculator, ScoreNormalizer
from scoring.tradeoffs import TradeOffAnalyzer
from optimizer.models import (
    OptimizationPlanResult,
    ScheduledBlockAssignment,
    MaintenanceRequestItem
)
from constraints.models import (
    BlockCandidate,
    BlockPlanCandidate,
    TrainMovementSummary,
    BlockWindowSummary,
    FeasibilityReport
)
from constraints.engine import ConstraintEngine, get_constraint_engine
from utils.logger import get_logger

logger = get_logger("plan_scoring_service")


class PlanScoringService:
    """
    Plan Scoring and Selection Engine.
    Operates on multiple feasible block plans generated by Prompt 7 OR-Tools,
    strictly validating feasibility via Prompt 6, calculating 13 operational metrics,
    computing 6 normalized sub-scores, determining weighted overall scores,
    and performing pairwise trade-off analysis.
    """

    def __init__(
        self,
        config: Optional[ScoringConfig] = None,
        constraint_engine: Optional[ConstraintEngine] = None,
        tradeoff_analyzer: Optional[TradeOffAnalyzer] = None
    ):
        self.config = config or get_default_scoring_config()
        self.constraint_engine = constraint_engine or get_constraint_engine()
        self.tradeoff_analyzer = tradeoff_analyzer or TradeOffAnalyzer(self.config)

    def score_plans(
        self,
        plans: List[OptimizationPlanResult],
        requests: List[MaintenanceRequestItem],
        trains: Optional[List[TrainMovementSummary]] = None,
        windows: Optional[List[BlockWindowSummary]] = None,
        corridor_code: str = "NDLS-CNB",
        horizon_start: Optional[datetime] = None,
        horizon_end: Optional[datetime] = None
    ) -> List[ScoredPlan]:
        """
        Validates, calculates metrics, and computes normalized/weighted scores for each plan.
        Infeasible plans are flagged and marked with their specific violation reasons.
        """
        scored_plans: List[ScoredPlan] = []
        train_list = trains or []
        win_list = windows or []

        for p in plans:
            # 1. Prompt 6 Hard Constraint Validation
            feasibility_report = self._validate_plan_with_constraint_engine(
                plan=p,
                trains=train_list,
                windows=win_list,
                corridor_code=corridor_code,
                horizon_start=horizon_start,
                horizon_end=horizon_end,
                requests=requests
            )

            is_feasible = feasibility_report.is_feasible
            rejection_reason = None
            if not is_feasible:
                violation_names = [v.violated_constraint for v in feasibility_report.violations]
                rejection_reason = f"Violated {len(feasibility_report.violations)} hard constraints: {', '.join(violation_names[:3])}"
                logger.warning("Plan [%s] rejected: %s", p.plan_reference, rejection_reason)

            # 2. Raw Metrics Calculation
            raw_metrics = PlanMetricsCalculator.calculate_metrics(
                plan=p,
                requests=requests,
                trains=train_list,
                windows=win_list,
                feasibility_report=feasibility_report
            )

            # 3. Score Normalization & Weighted Formulation
            normalized_scores = ScoreNormalizer.normalize(
                metrics=raw_metrics,
                total_requests_count=len(requests)
            )

            overall_score = ScoreNormalizer.compute_weighted_overall_score(
                normalized=normalized_scores,
                config=self.config
            )

            # If plan is infeasible, penalize overall score to 0.0 to prevent selection
            if not is_feasible:
                overall_score = 0.0

            sched_ids = [a.task_id for a in (p.scheduled_assignments or [])]
            unsched_ids = [u.task_id for u in (p.unscheduled_requests or [])]

            scored_plans.append(
                ScoredPlan(
                    plan_reference=p.plan_reference,
                    strategy=p.strategy.value if hasattr(p.strategy, "value") else str(p.strategy),
                    is_feasible=is_feasible,
                    rejection_reason=rejection_reason,
                    raw_metrics=raw_metrics,
                    normalized_scores=normalized_scores,
                    overall_score=overall_score,
                    scheduled_tasks_count=len(sched_ids),
                    unscheduled_tasks_count=len(unsched_ids),
                    scheduled_task_ids=sched_ids,
                    unscheduled_task_ids=unsched_ids
                )
            )

        return scored_plans

    def rank_plans(
        self,
        scored_plans: List[ScoredPlan]
    ) -> Tuple[List[ScoredPlan], List[ScoredPlan]]:
        """
        Ranks feasible plans descending by overall score with deterministic tie-breaking.
        Infeasible plans are separated into the second return list.
        """
        feasible = [p for p in scored_plans if p.is_feasible]
        infeasible = [p for p in scored_plans if not p.is_feasible]

        # Deterministic multi-key sorting
        def sort_key(p: ScoredPlan):
            norm = p.normalized_scores
            return (
                p.overall_score,
                norm.risk_priority_score if norm else 0.0,
                norm.operational_efficiency_score if norm else 0.0,
                norm.asset_availability_score if norm else 0.0,
                p.plan_reference  # Lexicographical tie-breaker
            )

        # Sort descending (except plan_reference which breaks ties deterministically)
        feasible.sort(key=sort_key, reverse=True)

        # Assign rank 1, 2, ...
        for idx, p in enumerate(feasible):
            p.rank = idx + 1

        return feasible, infeasible

    def select_best_plan(
        self,
        plans: List[OptimizationPlanResult],
        requests: List[MaintenanceRequestItem],
        trains: Optional[List[TrainMovementSummary]] = None,
        windows: Optional[List[BlockWindowSummary]] = None,
        corridor_code: str = "NDLS-CNB",
        horizon_start: Optional[datetime] = None,
        horizon_end: Optional[datetime] = None
    ) -> PlanSelectionResponse:
        """
        Full end-to-end evaluation: scores all candidate plans, filters out infeasible ones,
        ranks feasible plans, performs trade-off analysis against alternatives, and generates
        structured explanation data ready for Prompt 9.
        """
        if not plans:
            return PlanSelectionResponse(
                success=False,
                corridor_code=corridor_code,
                message="No candidate block plans provided for scoring."
            )

        # 1. Score all plans
        scored_plans = self.score_plans(
            plans=plans,
            requests=requests,
            trains=trains,
            windows=windows,
            corridor_code=corridor_code,
            horizon_start=horizon_start,
            horizon_end=horizon_end
        )

        # 2. Rank plans
        ranked_feasible, infeasible_plans = self.rank_plans(scored_plans)

        # 3. Check feasibility availability
        if not ranked_feasible:
            return PlanSelectionResponse(
                success=False,
                corridor_code=corridor_code,
                infeasible_plans=infeasible_plans,
                message="All candidate block plans were rejected due to hard constraint violations. No feasible plan available."
            )

        winning_plan = ranked_feasible[0]
        alternatives = ranked_feasible[1:]

        # Check minimum score threshold
        if winning_plan.overall_score < self.config.min_acceptable_score:
            logger.warning(
                "Winning plan %s scored %.2f, below minimum threshold %.2f",
                winning_plan.plan_reference, winning_plan.overall_score, self.config.min_acceptable_score
            )

        # 4. Pairwise Trade-Off Analysis & Why Winner Won
        all_tradeoffs: List[TradeOffItem] = []
        for alt in alternatives:
            t_list = self.tradeoff_analyzer.analyze_winner_vs_alternative(winning_plan, alt)
            all_tradeoffs.extend(t_list)

        why_winner_won = self.tradeoff_analyzer.generate_winning_reasons(winning_plan, alternatives)

        # 5. Score breakdown for winning plan
        score_breakdown = {}
        if winning_plan.normalized_scores:
            weights = self.config.get_normalized_weights()
            ns = winning_plan.normalized_scores
            score_breakdown = {
                "asset_availability": {
                    "raw_score": ns.asset_availability_score,
                    "weight": weights["asset_availability"],
                    "weighted_points": round(ns.asset_availability_score * weights["asset_availability"], 2)
                },
                "risk_priority": {
                    "raw_score": ns.risk_priority_score,
                    "weight": weights["risk_priority"],
                    "weighted_points": round(ns.risk_priority_score * weights["risk_priority"], 2)
                },
                "operational_efficiency": {
                    "raw_score": ns.operational_efficiency_score,
                    "weight": weights["operational_efficiency"],
                    "weighted_points": round(ns.operational_efficiency_score * weights["operational_efficiency"], 2)
                },
                "block_efficiency": {
                    "raw_score": ns.block_efficiency_score,
                    "weight": weights["block_efficiency"],
                    "weighted_points": round(ns.block_efficiency_score * weights["block_efficiency"], 2)
                },
                "grouping_efficiency": {
                    "raw_score": ns.grouping_efficiency_score,
                    "weight": weights["grouping_efficiency"],
                    "weighted_points": round(ns.grouping_efficiency_score * weights["grouping_efficiency"], 2)
                },
                "overdue_maintenance": {
                    "raw_score": ns.overdue_maintenance_score,
                    "weight": weights["overdue_maintenance"],
                    "weighted_points": round(ns.overdue_maintenance_score * weights["overdue_maintenance"], 2)
                },
                "total_composite_score": winning_plan.overall_score
            }

        # 6. Structured Explanation Payload for Prompt 9
        req_map = {r.task_id: r for r in requests}
        sched_prio_codes = [
            req_map[t_id].task_code for t_id in winning_plan.scheduled_task_ids
            if t_id in req_map and req_map[t_id].priority <= 2
        ]
        unsched_prio_codes = [
            req_map[t_id].task_code for t_id in winning_plan.unscheduled_task_ids
            if t_id in req_map and req_map[t_id].priority <= 2
        ]

        explanation_data = StructuredExplanationData(
            selected_plan=winning_plan.plan_reference,
            strategy=winning_plan.strategy,
            score=winning_plan.overall_score,
            metrics={
                "raw": winning_plan.raw_metrics.model_dump() if winning_plan.raw_metrics else {},
                "normalized": winning_plan.normalized_scores.model_dump() if winning_plan.normalized_scores else {}
            },
            key_decisions=why_winner_won,
            tradeoffs=[t.model_dump() for t in all_tradeoffs],
            scheduled_priority_tasks=sched_prio_codes,
            unscheduled_priority_tasks=unsched_prio_codes,
            major_constraints=[
                "15-minute passenger train headway buffers strictly maintained",
                "10-minute OHE electrical isolation buffers satisfied",
                "Crews and machinery capacities respected without overloading",
                "Asset corridor boundaries and dependencies checked"
            ],
            alternatives=[
                {
                    "plan_reference": alt.plan_reference,
                    "strategy": alt.strategy,
                    "rank": alt.rank,
                    "overall_score": alt.overall_score,
                    "high_risk_coverage": alt.raw_metrics.high_risk_maintenance_coverage if alt.raw_metrics else 0.0,
                    "corridor_disruption": alt.raw_metrics.corridor_disruption if alt.raw_metrics else 0.0
                }
                for alt in alternatives
            ]
        )

        return PlanSelectionResponse(
            success=True,
            corridor_code=corridor_code,
            selected_plan=winning_plan,
            score=winning_plan.overall_score,
            ranked_alternatives=alternatives,
            infeasible_plans=infeasible_plans,
            score_breakdown=score_breakdown,
            why_winner_won=why_winner_won,
            tradeoffs=all_tradeoffs,
            explanation_data=explanation_data,
            message=f"Selected plan '{winning_plan.plan_reference}' ({winning_plan.strategy}) with score {winning_plan.overall_score:.2f}/100."
        )

    def _validate_plan_with_constraint_engine(
        self,
        plan: OptimizationPlanResult,
        trains: List[TrainMovementSummary],
        windows: List[BlockWindowSummary],
        corridor_code: str,
        horizon_start: Optional[datetime],
        horizon_end: Optional[datetime],
        requests: Optional[List[MaintenanceRequestItem]] = None
    ) -> FeasibilityReport:
        """Converts plan into BlockPlanCandidate and executes Prompt 6 ConstraintEngine."""
        req_map = {r.task_id: r for r in (requests or [])}
        candidates: List[BlockCandidate] = []
        for a in (plan.scheduled_assignments or []):
            req = req_map.get(a.task_id)
            start_km = req.start_kilometer if req and req.start_kilometer is not None else 0.0
            end_km = req.end_kilometer if req and req.end_kilometer is not None else (start_km + 1.0)
            traffic_block = req.traffic_block_required if req and req.traffic_block_required is not None else True
            power_block = req.power_block_required if req and req.power_block_required is not None else False

            candidates.append(
                BlockCandidate(
                    candidate_id=a.assignment_id,
                    task_id=a.task_id,
                    task_code=a.task_code,
                    corridor_code=corridor_code,
                    department=a.department,
                    maintenance_type=a.maintenance_type,
                    asset_id=a.asset_id,
                    asset_code=a.asset_code,
                    start_kilometer=start_km,
                    end_kilometer=end_km,
                    traffic_block_required=traffic_block,
                    power_block_required=power_block,
                    start_time=a.start_time,
                    end_time=a.end_time,
                    duration_minutes=a.duration_minutes,
                    priority=a.priority,
                    assigned_window_id=a.assigned_window_id,
                    machinery_required=a.machinery_assigned,
                    crew_required=a.crews_assigned,
                    is_shadow_block=a.is_shadow_block,
                    parent_block_id=a.parent_task_id
                )
            )

        start_ts = horizon_start or (candidates[0].start_time if candidates else datetime.now(timezone.utc))
        end_ts = horizon_end or (candidates[-1].end_time if candidates else datetime.now(timezone.utc))

        plan_candidate = BlockPlanCandidate(
            plan_reference=plan.plan_reference,
            corridor_code=corridor_code,
            horizon_start=start_ts,
            horizon_end=end_ts,
            candidates=candidates
        )

        return self.constraint_engine.validate_plan(
            plan=plan_candidate,
            trains=trains,
            windows=windows
        )


def get_plan_scoring_service() -> PlanScoringService:
    """Dependency provider for PlanScoringService."""
    return PlanScoringService()
